/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdarg.h>
#include "stm32f407xx.h"
#include "uart2.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/* delay_ms(1000) produces roughly 1 second delay (rough calibration for 16 MHz clock) */
static void delay_ms(volatile uint32_t ms) {
  while (ms--) {
    // NOTE: at -O0 with volatile, each loop iteration costs several cycles, not just one NOP
    for (volatile uint32_t i = 0; i < 4000; ++i) { __asm__("nop"); }
  }
}

int main(void)
{
  // note: readback after clock enable lives in uart2_init() so enable these before calling
  RCC_AHB1ENR |= (1 << 3); // Set bit 3 in AHB1 bus to enable GPIOD clock (LEDs live here)
  RCC_APB2ENR |= (1 << 14); // bit 14 in APB2 bus enables SYSCFG clock
  uart2_init(); // uart2 setup

  GPIOD_MODER |= (1 << 24); // set PD12 (green LED) to output mode
  GPIOA_MODER &= ~(0x3 << 0); // clear bits for PA0 set to input mode (default, but explicit)
  GPIOA_PUPDR |= (1 << 1); // set PA0 to pull-down for button press
  
  // Loop forever
	while(1) {
    uart2_printf("LED %d SR=%x msg=%s\r\n", 10, USART2_SR, "test");
  }
}
