/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdarg.h>
#include "stm32f407xx.h"
#include "uart2.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
 * Peripheral setup summary:
 *   GPIOA  - clock ON, PA1 analog mode, PA2/PA3 AF7 (UART)
 *   GPIOD  - clock ON, PD12 AF2 (TIM4 => PWM)
 *   TIM2/4 - timer ON
 *   ADC1   - ADC1 ON
 *   USART2 - clock ON, 115200 baud, TX enabled
 *   NVIC   - ADC IRQ enabled
 */
static void init(void) {
  /* enable clocks */
  // note: readback after clock enable lives in uart2_init() so enable these before calling
  RCC_AHB1ENR |= (1 << 3); // enable GPIOD (LEDs) clock on AHB1 @ bit 3
  RCC_APB1ENR |= (1 << 0); // enable TIM2 clock on APB1 @ bit 0
  RCC_APB1ENR |= (1 << 2); // enable TIM4 clock on APB1 @ bit 2
  RCC_APB2ENR |= (1 << 8); // enable ADC1 clock on APB2 @ bit 8
  uart2_init(); // uart2 setup: enables GPIOA on AHB1 @ bit 0 (enables PA0-PA15)

  /* configure pins: TODO */
  GPIOD_MODER &= ~(0x3 << 24); // clear PD12 mode bits --> follow clear-then-set pattern for fields wider than 1 bit
  GPIOD_MODER |= (0x2 << 24); // set PD12 (green LED) to alternate function mode (10)
  GPIOD_AFRH &= ~(0xF << 16); // clear AF bits for PD12
  GPIOD_AFRH |= (0x2 << 16); // set AF2 (TIM4_CH1)
  GPIOA_MODER &= ~(0x3 << 2); // clear bits for PA1
  GPIOA_MODER |= (0x3 << 2); // set PA1 to analog mode (MODER = 11)
  
  /* configure NVIC and SysTick */
  NVIC_ISER0 |= (1 << 18); // enable ADC_IRQHandler => #18 in startup file
}

int main(void)
{
  init();
}
