/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdarg.h>
#include "stm32f407xx.h"
#include "uart2.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
 * Peripheral setup summary:
 *   GPIOA  - clock ON, PA1 analog mode, PA2/PA3 AF7 (UART)
 *   GPIOD  - clock ON, PD12 AF2 (TIM4 => PWM)
 *   TIM2/4 - timer ON
 *   ADC1   - ADC1 ON
 *   USART2 - clock ON, 115200 baud, TX enabled
 *   NVIC   - ADC IRQ enabled
 */
static void init(void) {
  /* enable clocks */
  // note: readback after clock enable lives in uart2_init() so enable these before calling
  RCC_AHB1ENR |= (1 << 3); // enable GPIOD (LEDs) clock on AHB1 @ bit 3
  RCC_APB1ENR |= (1 << 0); // enable TIM2 clock on APB1 @ bit 0
  RCC_APB1ENR |= (1 << 2); // enable TIM4 clock on APB1 @ bit 2
  RCC_APB2ENR |= (1 << 8); // enable ADC1 clock on APB2 @ bit 8
  uart2_init();            // uart2 setup: enables GPIOA on AHB1 @ bit 0 (enables PA0-PA15)

  /* configure pins */
  GPIOD_MODER &= ~(0x3 << 24);  // clear PD12 mode bits --> follow clear-then-set pattern for fields wider than 1 bit
  GPIOD_MODER |= (0x2 << 24);   // set PD12 (green LED) to alternate function mode (10)
  GPIOD_AFRH &= ~(0xF << 16);   // clear AF bits for PD12
  GPIOD_AFRH |= (0x2 << 16);    // set AF2 (TIM4_CH1)
  GPIOA_MODER &= ~(0x3 << 2);   // clear bits for PA1
  GPIOA_MODER |= (0x3 << 2);    // set PA1 to analog mode (MODER = 11)

  /* configure TIM4 for PWM output on PD12 */
  TIM4_CR1 = 0;         // reset control register 1
  TIM4_PSC = 16 - 1;    // set prescaler for a 1 MHz timer tick (16 MHz clock)/(15 + 1) = 1 MHz)
  TIM4_ARR = 1000 - 1;  // set auto-reload value (1000 ticks = 1kHz PWM frequency (1 MHz timer tick / 1000 ticks = 1 kHz PWM frequency))
  TIM4_CCMR1 = (0x6 << 4) | (1 << 3); // set PWM mode 1 for channel 1
  TIM4_CCER = (1 << 0); // enable channel 1 output: CC1E bit in CCER
  TIM4_CCR1 = 250;      // set capture/compare value (25% duty cycle for 1 kHz PWM frequency)
  TIM4_CR1 |= (1 << 0); // enable timer: CEN bit in CR1

  /* configure ADC1 for single conversion on PA1 (channel 1) */
  ADC1_SQR3 &= ~(0x1F << 0);  // clear sequence register
  ADC1_SQR3 |= (1 << 0);      // channel 1 (PA1) as first conversion
  ADC1_SQR1 &= ~(0xF << 20);  // sequence length = 1 conversion (L = 0000)
  ADC1_SMPR2 &= ~(0x7 << 3);  // clear sample time for channel 1
  ADC1_SMPR2 |= (0x5 << 3);   // 84 cycles sample time (bits [5:3] for ch1)
  ADC1_CR2 |= (1 << 0);       // ADON: turn on ADC

  /* configure NVIC */
  NVIC_ISER0 |= (1 << 18); // enable ADC_IRQHandler => #18 in startup file
}

int main(void)
{
  init();

  while (1) {
    ADC1_CR2 |= (1 << 30);          // SWSTART: trigger conversion
    while (!(ADC1_SR & (1 << 1)));  // wait for EOC flag

    uint32_t adc_val = ADC1_DR & 0xFFF; // read 12-bit result
    uint32_t duty = (adc_val * 999) / 4095;
    TIM4_CCR1 = duty;

    uart2_printf("ADC: %d  Duty: %d\r\n", adc_val, duty);
  }
}
